const SELL_THROUGH_DATA_KEYS = {
	PRODUCT_ID_BLANK: "Product ID (Blank)",
	START_WEEK: "Start Week",
	START_DATE: "Start Date",
	INITIAL_INVENTORY: "Initial Inventory",
	USAGE_QTY: "Usage Qty",
	DAMAGE_QTY: "Damage Qty",
	TOTAL_QTY: "Total Qty [Usage + Damage]",
	NUM_DAYS: "Num Days",
	INVENTORY_ADDITION: "Inventory Addition",
	TOTAL_INVENTORY: "Total Inventory",
	CLOSING_INVENTORY: "Closing Inventory",
	SELL_THROUGH_RATE: "Sell-Through Rate(%)",
	END_WEEK: "End Week",
	END_DATE: "End Date",
};
export const {
	CLOSING_INVENTORY,
	DAMAGE_QTY,
	END_DATE,
	END_WEEK,
	INITIAL_INVENTORY,
	INVENTORY_ADDITION,
	NUM_DAYS,
	PRODUCT_ID_BLANK,
	SELL_THROUGH_RATE,
	START_DATE,
	START_WEEK,
	TOTAL_INVENTORY,
	TOTAL_QTY,
	USAGE_QTY,
} = SELL_THROUGH_DATA_KEYS;

export default SELL_THROUGH_DATA_KEYS;
